# SPAX-030: nested static-vs-feedback comparison ------------------------------

.mk_compare_data <- function() {
  demand <- terra::rast(nrows = 2, ncols = 2)
  terra::values(demand) <- c(10, 20, 30, 40)

  d1 <- terra::rast(nrows = 2, ncols = 2)
  d2 <- terra::rast(nrows = 2, ncols = 2)
  terra::values(d1) <- c(1, 2, 4, 5)
  terra::values(d2) <- c(5, 4, 2, 1)
  distance <- c(d1, d2)
  names(distance) <- c("facility1", "facility2")

  supply <- c(facility1 = 30, facility2 = 45)
  list(demand = demand, distance = distance, supply = supply)
}

.mk_compare_ladder <- function(td) {
  list(
    huff = .huff_problem(td$demand, td$supply, td$distance,
                         family = "gaussian", kappa = 1 / 3),
    haae = .haae_problem(td$demand, td$supply, td$distance,
                         family = "gaussian", kappa = 1 / 3)
  )
}

.fit_compare_ladder <- function(problems, observed, output = "utilization") {
  .fit_problem_ladder(
    problems,
    observed = observed,
    init = c(sigma = 1.5),
    lower = c(sigma = 0.5),
    upper = c(sigma = 4),
    output = output,
    lambda = 0.7,
    tol = 1e-10,
    max_iter = 500,
    control = list(maxit = 25)
  )
}

test_that("the ladder must be able to show either leg winning", {
  td <- .mk_compare_data()
  problems <- .mk_compare_ladder(td)

  # feedback world: target generated by the HAAE equilibrium
  feedback_obs <- .solve_problem(
    problems$haae, theta = c(sigma = 2), lambda = 0.7,
    tol = 1e-10, max_iter = 500
  )$outputs$utilization
  feedback <- .fit_compare_ladder(problems, feedback_obs)
  ft <- feedback$table
  expect_lt(ft$loss[ft$label == "haae"], 1e-8)
  expect_gt(ft$loss[ft$label == "huff"], 100 * ft$loss[ft$label == "haae"])

  # static world: target generated by the one-pass static Huff
  static_obs <- .solve_problem(
    problems$huff, theta = c(sigma = 2)
  )$outputs$utilization
  static <- .fit_compare_ladder(problems, static_obs)
  st <- static$table
  expect_lt(st$loss[st$label == "huff"], 1e-8)
  expect_gt(st$loss[st$label == "haae"], 100 * st$loss[st$label == "huff"])
})

test_that("the ladder returns one comparable table over both legs", {
  td <- .mk_compare_data()
  problems <- .mk_compare_ladder(td)
  observed <- .solve_problem(
    problems$haae, theta = c(sigma = 2), lambda = 0.7,
    tol = 1e-10, max_iter = 500
  )$outputs$utilization

  out <- .fit_compare_ladder(problems, observed)
  expect_named(out, c("fits", "table"))
  expect_named(out$fits, c("huff", "haae"))
  expect_s3_class(out$fits$huff, "huff_problem_nfxp_fit")
  expect_s3_class(out$fits$haae, "haae_problem_nfxp_fit")

  tab <- out$table
  expect_equal(tab$label, c("huff", "haae"))
  expect_equal(tab$model, c("huff", "haae"))
  expect_equal(tab$family, c("gaussian", "gaussian"))
  expect_equal(tab$n_params, c(1L, 1L))
  expect_match(tab$theta, "^sigma=")
  expect_equal(tab$n_observed, c(2L, 2L))
  expect_true(all(is.finite(tab$loss)))
  expect_true(all(is.finite(tab$correlation)))
  expect_true(all(is.finite(tab$rmse)))
  expect_true(all(tab$solver_converged))
  expect_equal(tab$optim_convergence, c(0L, 0L))
  # static leg: one-pass solve, exactly zero spectral radius
  expect_equal(tab$solver_iters[tab$label == "huff"], 1L)
  expect_equal(tab$spectral_radius[tab$label == "huff"], 0)
})

test_that("ladders work for masked matrix flow targets", {
  td <- .mk_compare_data()
  problems <- .mk_compare_ladder(td)
  observed <- .solve_problem(
    problems$haae, theta = c(sigma = 2), lambda = 0.7,
    tol = 1e-10, max_iter = 500
  )$outputs$allocation
  observed[2, 1] <- NA  # one suppressed flow cell

  out <- .fit_compare_ladder(problems, observed, output = "allocation")
  tab <- out$table
  expect_equal(tab$n_observed, rep(length(observed) - 1L, 2L))
  expect_lt(tab$loss[tab$label == "haae"], 1e-8)
  expect_gt(tab$loss[tab$label == "huff"], tab$loss[tab$label == "haae"])
})

test_that("comparability guards reject mismatched fits", {
  td <- .mk_compare_data()
  problems <- .mk_compare_ladder(td)
  observed <- .solve_problem(problems$huff, theta = c(sigma = 2))$outputs$utilization

  fit_args <- list(
    init = c(sigma = 1.5), lower = c(sigma = 0.5), upper = c(sigma = 4),
    lambda = 0.7, tol = 1e-10, max_iter = 500, control = list(maxit = 10)
  )
  base <- suppressWarnings(do.call(.fit_problem_nfxp, c(
    list(problem = problems$huff, observed = observed), fit_args
  )))

  # different observed values (misspecified on purpose; boundary warning ok)
  other_obs <- suppressWarnings(do.call(.fit_problem_nfxp, c(
    list(problem = problems$haae, observed = observed * 2), fit_args
  )))
  expect_error(.compare_problem_fits(list(a = base, b = other_obs)),
               "different observed values")

  # different observation mask
  masked <- observed
  masked[1] <- NA
  other_mask <- suppressWarnings(do.call(.fit_problem_nfxp, c(
    list(problem = problems$haae, observed = masked), fit_args
  )))
  expect_error(.compare_problem_fits(list(a = base, b = other_mask)),
               "different observation masks")

  # different loss_args
  other_eta <- suppressWarnings(do.call(.fit_problem_nfxp, c(
    list(problem = problems$haae, observed = observed,
         loss_args = list(eta = 10)), fit_args
  )))
  expect_error(.compare_problem_fits(list(a = base, b = other_eta)),
               "different `loss_args`")

  # different output
  alloc <- .solve_problem(problems$haae, theta = c(sigma = 2), lambda = 0.7,
                          tol = 1e-10, max_iter = 500)$outputs$allocation
  other_output <- suppressWarnings(do.call(.fit_problem_nfxp, c(
    list(problem = problems$haae, observed = alloc, output = "allocation"),
    fit_args
  )))
  expect_error(.compare_problem_fits(list(a = base, b = other_output)),
               "different outputs")

  # different loss function (misspecified on purpose; boundary warning ok)
  other_loss <- suppressWarnings(do.call(.fit_problem_nfxp, c(
    list(problem = problems$haae, observed = observed,
         loss = function(predicted, observed, eta = 1) {
           sum(abs(predicted - observed))
         },
         gradient = FALSE), fit_args
  )))
  expect_error(.compare_problem_fits(list(a = base, b = other_loss)),
               "different loss functions")

  # degenerate lists
  expect_error(.compare_problem_fits(list(base)), "at least two")
  expect_error(.compare_problem_fits(list(a = base, a = base)), "unique labels")
})

test_that(".compare_problem_fits on precomputed fits matches the ladder table", {
  td <- .mk_compare_data()
  problems <- .mk_compare_ladder(td)
  observed <- .solve_problem(
    problems$haae, theta = c(sigma = 2), lambda = 0.7,
    tol = 1e-10, max_iter = 500
  )$outputs$utilization

  out <- .fit_compare_ladder(problems, observed)
  rebuilt <- .compare_problem_fits(out$fits)
  expect_equal(rebuilt, out$table)
})
